CREATE DATABASE haushaltsbuch;

USE haushaltsbuch;

CREATE TABLE kategorie(
IDKategorie INT AUTO_INCREMENT PRIMARY KEY,
bezeichnung VARCHAR(30) UNIQUE
);

CREATE TABLE artikel(
IDArtikel INT AUTO_INCREMENT PRIMARY KEY,
bezeichnung VARCHAR(30) NOT NULL,
notiz VARCHAR(100),
IDKategorie INT,
CONSTRAINT FK_kategorie_IDKategorie
	FOREIGN KEY(IDKategorie) REFERENCES kategorie(IDKategorie)
	ON DELETE SET NULL
	ON UPDATE CASCADE
);

CREATE TABLE einkauf_artikel(
posNr INT AUTO_INCREMENT PRIMARY KEY,
anzahl INT NOT NULL,
preis FLOAT NOT NULL,
luxus BOOLEAN DEFAULT '0',
IDArtikel INT,
CONSTRAINT FK_artikel_IDArtikel
	FOREIGN KEY(IDArtikel) REFERENCES artikel(IDArtikel)
	ON DELETE SET NULL
	ON UPDATE CASCADE
);

CREATE TABLE ort(
PLZ CHAR(5) NOT NULL PRIMARY KEY,
ortname VARCHAR(30) NOT NULL
);

CREATE TABLE laden(
IDLaden INT AUTO_INCREMENT PRIMARY KEY,
strasse VARCHAR(30) NOT NULL,
hausNr VARCHAR(5) NOT NULL,
PLZ CHAR(5),
CONSTRAINT FK_ort_PLZ
	FOREIGN KEY(PLZ) REFERENCES ort(PLZ)
	ON DELETE SET NULL
	ON UPDATE CASCADE
);

CREATE TABLE haendler(
IDHaendler INT AUTO_INCREMENT PRIMARY KEY,
haendlername VARCHAR(30),
IDLaden INT,
CONSTRAINT FK_laden_IDLaden
	FOREIGN KEY(IDLaden) REFERENCES laden(IDLaden)
	ON DELETE SET NULL
	ON UPDATE CASCADE
);

CREATE TABLE benutzer(
IDBenutzer INT AUTO_INCREMENT PRIMARY KEY,
geburtsdatum DATE,
nachname VARCHAR(30) NOT NULL,
vorname VARCHAR(30) NOT NULL,
budget FLOAT
);

CREATE TABLE einkauf(
belegNr INT PRIMARY KEY NOT NULL,
datum DATE NOT NULL,
IDBenutzer INT,
posNr INT,
IDHaendler INT,
CONSTRAINT FK_benutzer_IDBenutzer
	FOREIGN KEY(IDBenutzer) REFERENCES benutzer(IDBenutzer)
	ON DELETE SET NULL
	ON UPDATE CASCADE,
CONSTRAINT FK_einkauf_artikel_posNr
	FOREIGN KEY(posNr) REFERENCES einkauf_artikel(posNr)
	ON DELETE SET NULL
	ON UPDATE CASCADE,
CONSTRAINT FK_haendler_IDHaendler
	FOREIGN KEY(IDHaendler) REFERENCES haendler(IDHaendler)
	ON DELETE SET NULL
	ON UPDATE CASCADE
);
